server:
  port: 8077
  
spring:
  application:
    name: spring-turbine-server  
    
turbine:
  app-config: web-client,user-service
  cluster-name-expression: "'default'"   

eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone:  http://localhost:9001/eureka/    