server:
  port: 9001

spring:
   zipkin:
    base-url: http://localhost:8075/   
eureka:
  client:
    register-with-eureka: false #不需要注册自己本身
    fetch-registry: false #不需要拉取服务列表
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
      
  server:
    enable-self-preservation: true  #自我保护机制
    eviction-interval-timer-in-ms: 10000 #续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）
 
