server:
  port: 8082

spring:
  datasource:
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/Test?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.mchange.v2.c3p0.ComboPooledDataSource
  zipkin:
    base-url: http://127.0.0.1:8075
  sleuth:
    sampler:
      probability: 1.0    
  application:
    name: user-service
  jpa:
    show-sql: true
    
#  jackson:
#    serialization:
#      fail-on-empty-beans: false  #Jpa框架->对象转json会报错，改配置可以出来处理


eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

  client:
    service-url:
      defaultZone:  http://localhost:9001/eureka/
      
      
management:
  endpoints:
    web:
      exposure:
        include: '*'      
